export const Mangas = [

    {
        id: 1,
        Titulo: "Attack on Titan Volumen I",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK1.png",
        Precio: 8.990
    },
    {
        id: 2,
        Titulo: "Attack on Titan Volumen II",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK2.png",
        Precio: 8.990
    },
    {
        id: 3,
        Titulo: "Attack on Titan Volumen III",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK3.png",
        Precio: 8.990
    },
    {
        id: 4,
        Titulo: "Attack on Titan Volumen IV",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK4.png",
        Precio: 8.990
    },
    {
        id: 5,
        Titulo: "Attack on Titan Volumen V",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK5.png",
        Precio: 8.990
    },
    {
        id: 6,
        Titulo: "Attack on Titan Volumen VI",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK6.png",
        Precio: 8.990
    },
    {
        id: 7,
        Titulo: "Attack on Titan Volumen VII",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK7.png",
        Precio: 8.990
    },
    {
        id: 8,
        Titulo: "Attack on Titan Volumen VIII",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK8.png",
        Precio: 8.990
    },
    {
        id: 9,
        Titulo: "Attack on Titan Volumen IX",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK9.png",
        Precio: 8.990
    }/* ,
    {
        id: 10,
        Titulo: "Attack on Titan Volumen X",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK10.png",
        Precio: 8.990
    },
    {
        id: 11,
        Titulo: "Attack on Titan Volumen XI",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK11.png",
        Precio: 8.990
    },
    {
        id: 12,
        Titulo: "Attack on Titan Volumen XII",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK12.png",
        Precio: 8.990
    },
    {
        id: 13,
        Titulo: "Attack on Titan Volumen XIII",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK13.png",
        Precio: 8.990
    },
    {
        id: 14,
        Titulo: "Attack on Titan Volumen XIV",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK14.png",
        Precio: 8.990
    },
    {
        id: 15,
        Titulo: "Attack on Titan Volumen XV",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK15.png",
        Precio: 8.990
    },
    {
        id: 16,
        Titulo: "Attack on Titan Volumen XVI",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK16.png",
        Precio: 8.990
    },
    {
        id: 17,
        Titulo: "Attack on Titan Volumen XVII",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK17.png",
        Precio: 8.990
    },
    {
        id: 18,
        Titulo: "Attack on Titan Volumen XVIII",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK18.png",
        Precio: 8.990
    },
    {
        id: 19,
        Titulo: "Attack on Titan Volumen XIX",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK19.png",
        Precio: 8.990
    },
    {
        id: 20,
        Titulo: "Attack on Titan Volumen XX",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK20.png",
        Precio: 8.990
    },
    {
        id: 21,
        Titulo: "Attack on Titan Volumen XXI",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK21.png",
        Precio: 8.990
    },
    {
        id: 22,
        Titulo: "Attack on Titan Volumen XXIII",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK22.png",
        Precio: 8.990
    },
    {
        id: 23,
        Titulo: "Attack on Titan Volumen XXIV",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK24.png",
        Precio: 8.990
    },
    {
        id: 24,
        Titulo: "Attack on Titan Volumen XXV",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK25.png",
        Precio: 8.990
    },
    {
        id: 25,
        Titulo: "Attack on Titan Volumen XXVI",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK26.png",
        Precio: 8.990
    },
    {
        id: 26,
        Titulo: "Attack on Titan Volumen XXVII",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK27.png",
        Precio: 8.990
    },
    {
        id: 27,
        Titulo: "Attack on Titan Volumen XXVIII",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK28.png",
        Precio: 8.990
    },
    {
        id: 28,
        Titulo: "Attack on Titan Volumen XXIX",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK29.png",
        Precio: 8.990
    },
    {
        id: 29,
        Titulo: "Attack on Titan Volumen XXX",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK30.png",
        Precio: 8.990
    },
    {
        id: 30,
        Titulo: "Attack on Titan Volumen XXXI",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK31.png",
        Precio: 8.990
    },
    {
        id: 31,
        Titulo: "Attack on Titan Volumen XXXII",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK32.png",
        Precio: 8.990
    },
    {
        id: 32,
        Titulo: "Attack on Titan Volumen XXXIII",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK33.png",
        Precio: 8.990
    },
    {
        id: 33,
        Titulo: "Attack on Titan Volumen XXXIV",
        Autor: "Hajime Isayama",
        Obra: "Shingeki no Kyojin",
        Genero: "Noidea",
        Descripcion: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Deleniti fugiat necessitatibus omnis corrupti deserunt. Illo perferendis ab, iste quos fugiat natus! Cum suscipit nobis similique officia quas expedita, autem voluptatum!",
        Stock: 10,
        Estado: "Disponible",
        Imagen: "http://pillan.inf.uct.cl/~lrevillod/MangaStore/assets/Covers/SNK34.png",
        Precio: 8.990
    } */
]